config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'posts#index'
  resources :posts do
    post 'like', to:'like#post_like'
    post 'dislike', to:'like#post_dislike'
    post 'hate', to:'like#post_hate'
    post 'dishate', to:'like#post_dishate'
    resources :comments do
      post 'like', to:'like#comment_like'
      post 'dislike', to:'like#comment_dislike'
      post 'hate', to:'like#comment_hate'
      post 'dishate', to:'like#comment_dishate'
    end
  end

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post, :counter_cache => true
  has_many :comment_like, dependent: :destroy
  validates :name, presence: true
end

app/models/comment_like.rb
class CommentLike < ActiveRecord::Base
  belongs_to :comment
  belongs_to :user

  before_save :prevent_repeated_click
  after_save :add_counter
  before_destroy :sub_counter

  private
  def add_counter
    if self.status == 0
      count = self.comment.likes_count
      self.comment.update(likes_count: count+1)
    else
      count = self.comment.hates_count
      self.comment.update(hates_count: count+1)
    end
  end

  def sub_counter
    if self.status == 0
      count = self.comment.likes_count
      self.comment.update(likes_count: count-1)
    else
      count = self.comment.hates_count
      self.comment.update(hates_count: count-1)
    end
  end

  def prevent_repeated_click
    CommentLike.where(comment_id: self.comment_id, user_id: self.user_id).each do |record|
      record.destroy
    end
  end
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :post_likes, dependent: :destroy
  validates :title, presence: true
end

app/models/post_like.rb
class PostLike < ActiveRecord::Base
  belongs_to :post
  belongs_to :user

  before_save :prevent_repeated_click
  after_save :add_counter
  before_destroy :sub_counter

  private
  def add_counter
    if self.status == 0
      count = self.post.likes_count
      self.post.update(likes_count: count+1)
    else
      count = self.post.hates_count
      self.post.update(hates_count: count+1)
    end
  end

  def sub_counter
    if self.status == 0
      count = self.post.likes_count
      self.post.update(likes_count: count-1)
    else
      count = self.post.hates_count
      self.post.update(hates_count: count-1)
    end
  end

  def prevent_repeated_click
    PostLike.where(post_id: self.post_id, user_id: self.user_id).each do |record|
      record.destroy
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :posts, dependent: :destroy
  has_many :post_likes, dependent: :destroy
  has_many :comment_likes, dependent: :destroy

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :allow_delete?, only: [:destroy]

  def create
    @comment = Comment.new(comment_params)
    if @comment.save
      redirect_to post_path(id: params[:post_id]), notice: 'Comment was successfully created.'
    else
      redirect_to post_path(id: params[:post_id]), alert: @comment.errors.full_messages.first
    end
  end
  def destroy
    Comment.where(id: params[:id], post_id: params[:post_id]).first.destroy
    redirect_to post_path(id: params[:post_id]), notice: 'Comment was successfully destroyed.'
  end

  private
    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      cp = params.require(:comment).permit(:name, :email, :content)
      cp[:post_id] = params[:post_id]
      cp
    end
    def allow_delete?
      post = current_user.posts.where(id: params[:post_id]).first
      comment = post.comments.where(id: params[:id]).first
      if comment.nil?
        redirect_to post_path(id: params[:post_id]), alert: 'You are not able to do this.'
      end

    end
end

app/controllers/like_controller.rb
class LikeController < ApplicationController
  before_action :authenticate_user!
  # Post Part
  def post_like
    PostLike.create(status: 0, post_id: params[:post_id], user_id: current_user.id)
    redirect_to params[:ref] || '/'
  end

  def post_dislike
    like = PostLike.where(status: 0, post_id: params[:post_id], user_id: current_user.id).first
    like.destroy
    redirect_to params[:ref] || '/'
  end

  def post_hate
    PostLike.create(status: 1, post_id: params[:post_id], user_id: current_user.id)
    redirect_to params[:ref] || '/'
  end

  def post_dishate
    like = PostLike.where(status: 1, post_id: params[:post_id], user_id: current_user.id).first
    like.destroy
    redirect_to params[:ref] || '/'
  end

  # Comment Part
  def comment_like
    CommentLike.create(status: 0, comment_id: params[:comment_id], user_id: current_user.id)
    redirect_to params[:ref] || '/'
  end

  def comment_dislike
    like = CommentLike.where(status: 0, comment_id: params[:comment_id], user_id: current_user.id).first
    like.destroy
    redirect_to params[:ref] || '/'
  end

  def comment_hate
    CommentLike.create(status: 1, comment_id: params[:comment_id], user_id: current_user.id)
    redirect_to params[:ref] || '/'
  end

  def comment_dishate
    like = CommentLike.where(status: 1, comment_id: params[:comment_id], user_id: current_user.id).first
    like.destroy
    redirect_to params[:ref] || '/'
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  def index
    @posts = Post.includes(:user).order(created_at: :desc).page params[:page]
    post_likes = current_user.post_likes.where(id: @posts.map(&:id)) rescue nil
    @user_likes = post_likes.map{|l| l.post_id if l.status == 0} rescue []
    @user_hates = post_likes.map{|l| l.post_id if l.status == 1} rescue []
  end

  def show
    @post = Post.where(id: params[:id]).includes(:user).first
    @comments = @post.comments.order(created_at: :desc).page params[:page]

    # Query user like/hate list by one query and store them to array
    post_like = current_user.post_likes.where(post_id: params[:id]).first rescue nil
    @user_post_like = (post_like.status == 0) rescue false
    @user_post_hate = (post_like.status == 1) rescue false
    comment_likes = current_user.comment_likes.where(comment_id: @post.comments.map(&:id)) rescue nil
    @user_comment_likes = comment_likes.map{|c| c.comment_id if c.status == 0} rescue []
    @user_comment_hates = comment_likes.map{|c| c.comment_id if c.status == 1} rescue []

    @new_comment = Comment.new(post_id: params[:id])
  end

  def new
    @post = current_user.posts.new
  end

  def edit
    @post = current_user.posts.where(id: params[:id]).first
  end

  def create
    @post = current_user.posts.new(post_params)
    if @post.save
      redirect_to @post, notice: 'Post was successfully created.'
    else
      render :new
    end
  end

  def update
      if @post.update(post_params)
        redirect_to @post, notice: 'Post was successfully updated.'
      else
        render :edit
      end
  end

  def destroy
    @post = current_user.posts.where(id: params[:id]).first
    @post.destroy
    redirect_to posts_url, notice: 'Post was successfully destroyed.'
  end

  private
    def post_params
      params.require(:post).permit(:title, :content)
    end

    def allow_change?
      @post = current_user.posts.where(id: params[:id]).first
      redirect_to posts_url, alert: 'You are not able to do this.' if @post.nil?
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/like_helper.rb
module LikeHelper

end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>My Blog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

</head>
<body>
  <nav class="navbar navbar-default navbar-inverse navbar-fixed-top">
    <div class="container-fluid">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to raw('<span class="glyphicon glyphicon-home"></span> MY BLOG'), root_path, class: 'navbar-brand' %>
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
          <li <%= raw('class="active"') if params[:controller] == 'posts' %>><%= link_to raw('<span class="glyphicon glyphicon-book"></span> Articles'), posts_path %></li>
          <li <%= raw('class="active"') if params[:controller] == 'devise/registrations' %>><%= link_to raw('<span class="glyphicon glyphicon-book"></span> Register'), new_user_registration_path %></li>
        </ul>

        <ul class="nav navbar-nav navbar-right">
          <% if current_user.nil? %>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                  Login
                  <span class="caret"></span>
                </a>
                <ul class="dropdown-menu" style="min-width: 300px; padding-left: 10px; padding-right: 10px;">
                  <%= form_for(resource, as: resource_name, url: session_path(resource_name), class: 'navbar-form') do |f|%>
                      <div class="form-group">
                        <%= f.label :email %>
                        <%= f.email_field :email, class: 'form-control' %>
                      </div>
                      <div class="form-group">
                        <%= f.label :password %>
                        <%= f.password_field :password, class: 'form-control' %>
                      </div>
                      <div class="form-group">
                        <%= f.check_box :remember_me %>
                        <%= f.label :remember_me %>
                      </div>
                      <div class="text-center" style="padding-top: 5px;">
                        <%= f.submit 'Log in', class: 'btn btn-default' %>
                      </div>
                  <% end %>
                </ul>
              </li>

          <% else %>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                Signed in as <%= current_user.username %>
                <span class="caret"></span>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to 'Logout', destroy_user_session_path, method: :delete %></li>
              </ul>
            </li>
          <% end %>
        </ul>
      </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
  </nav>

  <div class="container">
    <% if alert %>
        <div class="alert alert-danger alert-dismissible" role="alert">
          <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          <strong>Alert! </strong> <%= alert %>
        </div>
    <% elsif notice %>
        <div class="alert alert-warning alert-dismissible" role="alert">
          <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          <strong>Notice. </strong> <%= notice %>
        </div>
    <% end %>
    <%= yield %>
  </div>
</body>
</html>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>
      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_field :content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<div class="row">
  <div class="col-xs-12 col-md-8 col-md-offset-2 text-center">
    <h1>Posts List</h1>
    <%=  link_to 'New Article', new_post_path, class: 'btn btn-primary', style: 'margin-bottom: 5px;' %>
  </div>
</div>
<div class="row">
  <div class="col-xs-12 col-md-10 col-md-offset-1 text-center">
    <%= paginate @posts %>
  </div>
</div>
<div class="row">
  <div class="col-xs-12 col-md-10 col-md-offset-1">
    <% @posts.each do |post| %>
        <div class="panel panel-default">
          <div class="panel-heading clearfix">
            <h4 class="pull-left">
              <%= truncate(post.title, length: 50)%>
            </h4>
            <span class="pull-right">
                <img src="<%= post.user.avatar_path %>" width="40px" class="img-thumbnail"/>
              <%= mail_to post.user.email, post.user.username  %>
            </span>
          </div>
          <div class="panel-body">
            <%=truncate(post.content, length: 100)%>
          </div>
          <div class="panel-footer clearfix">
            <div class="pull-left">
              <%= post.likes_count %>
              <% if !@user_likes.include? post.id %>
                  <%= link_to raw('Like <span class="glyphicon glyphicon-thumbs-up"></span>'), post_like_path(post_id: post.id, ref: request.fullpath), class: 'btn btn-primary btn-xs', method: :post %>
              <% else %>
                  <%= link_to raw('Dislike X'), post_dislike_path(post_id: post.id, ref: request.fullpath), class: 'btn btn-primary btn-xs', method: :post %>
              <% end %>
              <%= post.hates_count %>
              <% if !@user_hates.include? post.id %>
                  <%= link_to raw('Hate <span class="glyphicon glyphicon-thumbs-down"></span>'), post_hate_path(post_id: post.id, ref: request.fullpath), class: 'btn btn-danger btn-xs', method: :post %>
              <% else %>
                  <%= link_to raw('Dishate X'), post_dishate_path(post_id: post.id, ref: request.fullpath), class: 'btn btn-danger btn-xs', method: :post %>
              <% end %>
              Posted Date: <%= post.created_at %>
            </div>
            <div class="pull-right">
              <%= post.comments.size %> <span class="glyphicon glyphicon-comment"></span>
              <% if post.user == current_user %>
                  <%= link_to raw('<span class="glyphicon glyphicon-remove-circle"></span> Delete'), post_path(id: post.id), class: 'btn btn-danger btn-xs', method: :delete, data: {confirm: 'Are you sure?'}%>
                  <%= link_to raw('<span class="glyphicon glyphicon-edit"></span> Edit'), edit_post_path(id: post.id), class: 'btn btn-warning btn-xs'%>
              <% end %>
              <%= link_to raw('<span class="glyphicon glyphicon-eye-open"></span> Read more'), post_path(id: post.id), class: 'btn btn-success btn-xs'%>
            </div>
          </div>
        </div>
    <% end %>
  </div>
</div>

</div>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<div class="row">
  <div id="show_post_content" class="col-xs-12 col-md-10 col-md-offset-1">
    <h3 id="show_post_title" class="text-center"> <%= @post.title %> </h3>
    <p id="show_article">
      <%= @post.content %>
    </p>
    <div id="show_control_block" class="clearfix">
      <span class="pull-left">
        <i> <%= @post.created_at %> posted by</i>
          <%= image_tag @post.user.avatar_path, class: 'img-thumbnail', width: '40px'%> <%= @post.user.username %>
      </span>
      <div class="pull-right">
        <% if @post.user == current_user %>
            <%= link_to raw('<span class="glyphicon glyphicon-remove-circle"></span> Delete'), post_path(id: @post.id), class: 'btn btn-danger btn-xs', method: :delete, data: {confirm: 'Are you sure?'}%>
            <%= link_to raw('<span class="glyphicon glyphicon-edit"></span> Edit'), edit_post_path(id: @post.id), class: 'btn btn-warning btn-xs'%>
        <% end %>
        <%= @post.likes_count %>
        <% if @user_post_like.nil? %>
            <%= link_to raw('Like <span class="glyphicon glyphicon-thumbs-up"></span>'), post_like_path(post_id: @post.id, ref: request.fullpath), class: 'btn btn-primary btn-xs', method: :post %>
        <% else %>
            <%= link_to raw('Dislike X'), post_dislike_path(post_id: @post.id, ref: request.fullpath), class: 'btn btn-primary btn-xs', method: :post %>
        <% end %>
        <%= @post.hates_count %>
        <% if @user_post_hate.nil? %>
            <%= link_to raw('Hate <span class="glyphicon glyphicon-thumbs-down"></span>'), post_hate_path(post_id: @post.id, ref: request.fullpath), class: 'btn btn-danger btn-xs', method: :post %>
        <% else %>
            <%= link_to raw('Dishate X'), post_dishate_path(post_id: @post.id, ref: request.fullpath), class: 'btn btn-danger btn-xs', method: :post %>
        <% end %>
      </div>
    </div>
    <h3 class="text-center"> Comments </h3>
    <%= form_for [@post, @new_comment],html: {id: 'show_comment_form'} do |f| %>
        <div class="form-group">
          <%= f.label :name %>
          <%= f.text_field :name, class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.label :email %>
          <%= f.text_field :email, class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.label :content %>
          <%= f.text_area :content, class: 'form-control' %>
        </div>
        <div class="text-center">
          <%= f.submit 'Submit', class: 'btn btn-success' %>
        </div>
    <% end %>
    <% @comments.each do |comment| %>
        <div class="panel panel-default">
          <div class="panel-heading clearfix">
            <span class="pull-left">
              Name:
              <%= comment.name %>
            </span>
            <span class="pull-right">
              Email:
              <%= mail_to comment.email %>
            </span>
          </div>
          <div class="panel-body">
            <%= comment.content %>
          </div>
          <div class="panel-footer clearfix">
            <div class="pull-left">
              Posted Date: <%= comment.id  %>
            </div>
            <div class="pull-right">
              <% if @post.user == current_user %>
                  <%= link_to raw('<span class="glyphicon glyphicon-remove-circle"></span> Delete'), post_comment_path(id: comment.id, post_id: @post.id), class: 'btn btn-danger btn-xs', method: :delete, data: {confirm: 'Are you sure?'}%>
              <% end %>
              <%= comment.likes_count %>
              <% if !@user_comment_likes.include? comment.id %>
                  <%= link_to raw('Like <span class="glyphicon glyphicon-thumbs-up"></span>'), post_comment_like_path(post_id: @post.id, comment_id: comment.id, ref: request.fullpath), class: 'btn btn-primary btn-xs', method: :post %>
              <% else %>
                  <%= link_to raw('Dislike X'), post_comment_dislike_path(post_id: @post.id, comment_id: comment.id, ref: request.fullpath), class: 'btn btn-primary btn-xs', method: :post %>
              <% end %>
              <%= comment.hates_count %>
              <% if !@user_comment_hates.include? comment.id %>
                  <%= link_to raw('Hate <span class="glyphicon glyphicon-thumbs-down"></span>'), post_comment_hate_path(post_id: @post.id, comment_id: comment.id, ref: request.fullpath), class: 'btn btn-danger btn-xs', method: :post %>
              <% else %>
                  <%= link_to raw('Dishate X'), post_comment_dishate_path(post_id: @post.id, comment_id: comment.id, ref: request.fullpath), class: 'btn btn-danger btn-xs', method: :post %>
              <% end %>
            </div>
          </div>
        </div>
    <% end %>
    <div class="text-center">
      <%= paginate @comments %>
    </div>
  </div>
</div>